//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArTransPost
    {
        public int Id { get; set; }
        public System.DateTime DtPost { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
        public int ArTransactionId { get; set; }
    
        public virtual ArTransaction ArTransaction { get; set; }
    }
}
