//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArAccntCredit
    {
        public int Id { get; set; }
        public int ArAccountId { get; set; }
        public System.DateTime DtCredit { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal OverLimitAllowed { get; set; }
        public decimal CreditWarning { get; set; }
        public string ApprovedBy { get; set; }
        public int ArCreditStatusId { get; set; }
    
        public virtual ArAccount ArAccount { get; set; }
        public virtual ArCreditStatus ArCreditStatu { get; set; }
    }
}
