//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArAccntTerm
    {
        public int Id { get; set; }
        public System.DateTime dtTerm { get; set; }
        public int NoOfDays { get; set; }
        public string Remarks { get; set; }
        public int ArAccountId { get; set; }
        public string ApprovedBy { get; set; }
        public int ArAccntTermStatusId { get; set; }
    
        public virtual ArAccount ArAccount { get; set; }
        public virtual ArAccntTermStatus ArAccntTermStatu { get; set; }
    }
}
