//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArDeposit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArDeposit()
        {
            this.ArTransDeposits = new HashSet<ArTransDeposit>();
        }
    
        public int Id { get; set; }
        public System.DateTime DtDeposit { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public string Reference { get; set; }
        public int ArDepositBankId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArTransDeposit> ArTransDeposits { get; set; }
        public virtual ArDepositBank ArDepositBank { get; set; }
    }
}
