//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArPayment()
        {
            this.ArTransPayments = new HashSet<ArTransPayment>();
        }
    
        public int Id { get; set; }
        public System.DateTime DtPayment { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public string Reference { get; set; }
        public int ArAccountId { get; set; }
        public int ArPaymentTypeId { get; set; }
        public Nullable<bool> IsDeposited { get; set; }
        public Nullable<System.DateTime> DtDeposit { get; set; }
    
        public virtual ArAccount ArAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArTransPayment> ArTransPayments { get; set; }
        public virtual ArPaymentType ArPaymentType { get; set; }
    }
}
